ALTER TABLE public.marche_fulfillment_transitions
  ADD COLUMN IF NOT EXISTS seq bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.marche_fulfillment_transitions
  ALTER COLUMN created_at SET DEFAULT clock_timestamp();
CREATE INDEX IF NOT EXISTS marche_fulfillment_transitions_seq_idx
  ON public.marche_fulfillment_transitions(order_id, seq);

CREATE OR REPLACE FUNCTION public._marche_fulfillment_apply(
  p_order_id uuid, p_to text, p_actor uuid, p_role text, p_reason text)
RETURNS public.marche_orders LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE o public.marche_orders; v_from text; v_now timestamptz := clock_timestamp();
BEGIN
  SELECT * INTO o FROM public.marche_orders WHERE id = p_order_id FOR UPDATE;
  IF o.id IS NULL THEN RAISE EXCEPTION 'ORDER_NOT_FOUND'; END IF;
  v_from := o.fulfillment_state;
  PERFORM set_config('marche.rpc','1', true);
  UPDATE public.marche_orders
     SET fulfillment_state = p_to,
         fulfillment_updated_at = v_now,
         accepted_at  = CASE WHEN p_to='accepted'  AND accepted_at  IS NULL THEN v_now ELSE accepted_at  END,
         ready_at     = CASE WHEN p_to='ready'     AND ready_at     IS NULL THEN v_now ELSE ready_at     END,
         delivered_at = CASE WHEN p_to='delivered' AND delivered_at IS NULL THEN v_now ELSE delivered_at END,
         rejected_at  = CASE WHEN p_to='rejected'  AND rejected_at  IS NULL THEN v_now ELSE rejected_at  END
   WHERE id = o.id RETURNING * INTO o;
  INSERT INTO public.marche_fulfillment_transitions(order_id, from_state, to_state, actor_id, actor_role, mission_id, reason, created_at)
  VALUES (o.id, v_from, p_to, p_actor, p_role, o.mission_id, NULLIF(btrim(COALESCE(p_reason,'')),''), v_now);
  PERFORM set_config('marche.rpc','', true);
  RETURN o;
END $$;

CREATE OR REPLACE FUNCTION public.marche_order_fulfillment_history(p_order_id uuid)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
DECLARE caller uuid := auth.uid(); o public.marche_orders; v_admin boolean;
BEGIN
  IF caller IS NULL THEN RAISE EXCEPTION 'AUTH_REQUIRED'; END IF;
  SELECT * INTO o FROM public.marche_orders WHERE id = p_order_id;
  IF o.id IS NULL THEN RAISE EXCEPTION 'ORDER_NOT_FOUND'; END IF;
  v_admin := public.is_any_admin(caller);
  IF o.buyer_user_id <> caller AND o.merchant_user_id <> caller AND NOT v_admin THEN
    RAISE EXCEPTION 'NOT_AUTHORIZED';
  END IF;
  RETURN COALESCE((
    SELECT jsonb_agg(jsonb_build_object(
      'from_state', t.from_state, 'to_state', t.to_state,
      'actor_role', t.actor_role, 'reason', t.reason, 'at', t.created_at)
      || CASE WHEN v_admin THEN jsonb_build_object('actor_id', t.actor_id, 'mission_id', t.mission_id)
              ELSE '{}'::jsonb END
      ORDER BY t.seq)
    FROM public.marche_fulfillment_transitions t WHERE t.order_id = o.id), '[]'::jsonb);
END $$;

REVOKE ALL ON FUNCTION public.marche_order_fulfillment_history(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.marche_order_fulfillment_history(uuid) TO authenticated;
REVOKE ALL ON FUNCTION public._marche_fulfillment_apply(uuid, text, uuid, text, text) FROM PUBLIC, anon, authenticated;

DO $do$
DECLARE s text;
BEGIN
  SELECT prosrc INTO s FROM pg_proc WHERE proname='_qa_node4_marche_r5';
  s := replace(s,
    '(SELECT string_agg(to_state, ''>'' ORDER BY created_at, id)',
    '(SELECT string_agg(to_state, ''>'' ORDER BY seq)');
  EXECUTE format('CREATE OR REPLACE FUNCTION public._qa_node4_marche_r5() RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS %L', s);
END $do$;
REVOKE ALL ON FUNCTION public._qa_node4_marche_r5() FROM PUBLIC, anon, authenticated;

DELETE FROM public._qa_s13_results WHERE part = 45;
INSERT INTO public._qa_s13_results(part, result) VALUES (45, public._qa_node4_marche_r5());