ALTER FUNCTION public._qa_s13_run4() SECURITY INVOKER;
ALTER FUNCTION public._qa_s13_run5() SECURITY INVOKER;
ALTER FUNCTION public._qa_s13_run6() SECURITY INVOKER;
ALTER FUNCTION public._qa_s13_run7() SECURITY INVOKER;