ALTER FUNCTION public._qa_s13_run4() SECURITY DEFINER;
ALTER FUNCTION public._qa_s13_run5() SECURITY DEFINER;
ALTER FUNCTION public._qa_s13_run6() SECURITY DEFINER;
ALTER FUNCTION public._qa_s13_run7() SECURITY DEFINER;
REVOKE ALL ON FUNCTION public._qa_s13_run4() FROM PUBLIC;
REVOKE ALL ON FUNCTION public._qa_s13_run4() FROM anon;
REVOKE ALL ON FUNCTION public._qa_s13_run4() FROM authenticated;
REVOKE ALL ON FUNCTION public._qa_s13_run5() FROM PUBLIC;
REVOKE ALL ON FUNCTION public._qa_s13_run5() FROM anon;
REVOKE ALL ON FUNCTION public._qa_s13_run5() FROM authenticated;
REVOKE ALL ON FUNCTION public._qa_s13_run6() FROM PUBLIC;
REVOKE ALL ON FUNCTION public._qa_s13_run6() FROM anon;
REVOKE ALL ON FUNCTION public._qa_s13_run6() FROM authenticated;
REVOKE ALL ON FUNCTION public._qa_s13_run7() FROM PUBLIC;
REVOKE ALL ON FUNCTION public._qa_s13_run7() FROM anon;
REVOKE ALL ON FUNCTION public._qa_s13_run7() FROM authenticated;
GRANT EXECUTE ON FUNCTION public._qa_s13_run4() TO service_role;
GRANT EXECUTE ON FUNCTION public._qa_s13_run5() TO service_role;
GRANT EXECUTE ON FUNCTION public._qa_s13_run6() TO service_role;
GRANT EXECUTE ON FUNCTION public._qa_s13_run7() TO service_role;