DROP FUNCTION IF EXISTS public.admin_set_finance_policy(
  p_mission_type text,
  p_commission_bps integer,
  p_min_driver_balance_gnf bigint,
  p_collateral_mode text,
  p_collateral_pct_bps integer,
  p_collateral_fixed_gnf bigint,
  p_collateral_min_gnf bigint,
  p_collateral_max_gnf bigint,
  p_fixed_commission_gnf bigint,
  p_require_collateral_before_offer boolean,
  p_effective_from timestamptz,
  p_note text,
  p_collateral_basis text,
  p_transaction_fee_bps integer,
  p_fee_basis text,
  p_cancel_before_dispatch_bps integer,
  p_cancel_after_dispatch_bps integer,
  p_cancel_basis text,
  p_cash_funding_mode text,
  p_cash_funding_pct_bps integer,
  p_cash_funding_max_gnf bigint,
  p_max_declared_value_gnf bigint
);